### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by yoodame** [TheLarkInn/angular-starter-es6-webpack#6]
While running `$ npm dev`, the console logs "Uncaught RangeError: Maximum call stack size exceeded" error after saving changes.

SOLUTION: [https://github.com/webpack/webpack-dev-server/issues/87]()
REASON: "You shouldn't be doing `--hot` and `new webpack.HotModuleReplacementPlugin()` in `webpack.config.js > plugins: [] section` simultaneously."

**Comment by TheLarkInn** [comment]
Thanks for reporting this. I'll have to look at this but it appears your sayings its doing the same thing twice.

**Comment by TheLarkInn** [comment]
I see, nice catch. I'll go ahead get something in, unless you'd like to submit a pull request. :smirk:

**Comment by TheLarkInn** [comment]
Fixed with f6323ad52dcb362d86b90c53fa684b1d5f634631
